### ISSUE TITLE
希望增加 shadowsocks 自动代理

### ISSUE THREAD

**Issue by weiyideai520** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER-ADDONS#1]
其他我安装插件，就只需要这一个功能就够了，还请麻烦支持一下吧。
如果你还有别的 推荐吗，基于官方的固件 做的，安装在U盘里的 shadowsocks

**Comment by JACK-THINK** [comment]
完美透明代理做不到，因为官方固件不支持tproxy，没法代理UDP流量
