### ISSUE TITLE
VLMCSD 1113 Release

### ISSUE THREAD

**Issue by PC-Pilot** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER-ADDONS#3]
Not sure if this information is useful but just a polite notice to advise of latest VLMCSD update release (to V1113, see <https://forums.mydigitallife.net/threads/emulated-kms-servers-on-non-windows-platforms.50234/>) :

Source and binaries: <https://www.upload.ee/files/11363704/vlmcsd-1113-2020-03-28-Hotbird64.7z.html> 
Source only: <https://www.upload.ee/files/11363713/vlmcsd-1113-2020-03-28-Hotbird64-source-only.7z.html>
7z password is 2020

Source and binaries checksums:
SHA256: 16f06ca6d377bc4b8ebbf2aaf3fafba6cd484e017f432cfdd9cf3a7af100c841
SHA1: ed5310ce6c0cad526feef81e5fc712fe07f55b36
MD5: 99752a4ca7a6da3e0917230a4b29fe80

CHANGES
2020-03-28 (1113)
.kmd file format changed to version 2.0 (version 1.x files cannot be used any more)
host builds are now configurable in the .kmd file
Bugfix: vlmcs did not use the configured CSVLKs when used with -G
Bugfix: .kmd file version was not displayed correctly on big-endian systems
Bugfix: Posix versions of vlmcsd were unable to read MS-DOS/Windows text files with crlf line termination
Bugfix: the NO_INI_FILE CFLAG did not work in combination with some other directives
New CFLAG NO_COMPILER_UAA disables all compiler/platform support for big-endian/little-endian conversion. Required on some toolchains that are incorrectly configured
The bootable floppy directory now contains a .vmx file that can be used to directly start the floppy in VMware products, e.g. the free VMware player
When you use -v all CSVLK available in the .kmd file are now logged at program startup.
If you do not use -N0 or -N1 to force disable/enable the NDR64 protocol, vlmcsd now uses the host build to decide if it uses NDR64 depending if a genuine KMS is using NDR64 on that build.

**Comment by JACK-THINK** [comment]
@PC-Pilot 

Thanks a lot. I have made a update of vlmcsd in version 16.2.
